
poll_interval_seconds: 60

projects:
- name: Transiter
  github_user: jamespfennell
  repo: transiter
  mainline_branch: master
  working_directory: /home/james/801X-transiter-go
  steps:
  - name: Pull
    run: docker-compose pull
  - name: Redeploy Transiter
    run: docker-compose up -d transiter
  - name: Redeploy Transiter docs
    run: docker-compose up -d transiter-docs
  - name: Wait for 5 seconds
    run: sleep 5
  - name: Ping demo.transiter.dev
    run: curl --fail-with-body -v https://demo.transiter.dev/systems/us-ny-subway --output /dev/null

- name: realtimerail.nyc
  github_user: jamespfennell
  repo: realtimerail.nyc
  mainline_branch: master
  working_directory: /home/james/7001-realtimerail-ui-new
  steps:
  - name: Pull
    run: docker-compose pull
  - name: Redeploy
    run: docker-compose up -d

- name: PATH train GTFS
  github_user: jamespfennell
  repo: path-train-gtfs-realtime
  mainline_branch: master
  working_directory: /home/james/9000-path-train-gtfs-realtime
  steps:
  - name: Pull
    run: docker-compose pull
  - name: Redeploy
    run: docker-compose up -d
  - name: Wait for 5 seconds
    run: sleep 5
  - name: Ping path.transitdata.nyc
    run: curl --fail-with-body -v https://path.transitdata.nyc/gtfsrt --output /dev/null

- name: Texcraft
  github_user: jamespfennell
  repo: texcraft
  mainline_branch: main
  working_directory: /home/james/301X-texcraft.dev
  wait_minutes: 100000000
  steps:
  - name: Pull
    run: docker-compose pull
  - name: Redeploy
    run: docker-compose up -d
  - name: Wait for 5 seconds
    run: sleep 5
  - name: Ping texcraft.dev
    run: curl --fail-with-body -v https://texcraft.dev --output /dev/null
  - name: Ping play.texcraft.dev
    run: curl --fail-with-body -v https://play.texcraft.dev --output /dev/null




