
poll_interval_seconds: 10

projects:
- name: Transiter
  github_user: jamespfennell
  repo: transiter
  mainline_branch: master
  steps:
  - name: Pull Docker image
    run: ls -lah
  - name: Recreate the Docker container
    run: ls ds

- name: realtimerail.nyc
  github_user: jamespfennell
  repo: realtimerail.nyc
  mainline_branch: master
